require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CreatorsController do

  # This should return the minimal set of attributes required to create a valid
  # Creator. As you add validations to Creator, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all creators as @creators" do
      creator = Creator.create! valid_attributes
      get :index
      assigns(:creators).should eq([creator])
    end
  end

  describe "GET show" do
    it "assigns the requested creator as @creator" do
      creator = Creator.create! valid_attributes
      get :show, :id => creator.id.to_s
      assigns(:creator).should eq(creator)
    end
  end

  describe "GET new" do
    it "assigns a new creator as @creator" do
      get :new
      assigns(:creator).should be_a_new(Creator)
    end
  end

  describe "GET edit" do
    it "assigns the requested creator as @creator" do
      creator = Creator.create! valid_attributes
      get :edit, :id => creator.id.to_s
      assigns(:creator).should eq(creator)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Creator" do
        expect {
          post :create, :creator => valid_attributes
        }.to change(Creator, :count).by(1)
      end

      it "assigns a newly created creator as @creator" do
        post :create, :creator => valid_attributes
        assigns(:creator).should be_a(Creator)
        assigns(:creator).should be_persisted
      end

      it "redirects to the created creator" do
        post :create, :creator => valid_attributes
        response.should redirect_to(Creator.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved creator as @creator" do
        # Trigger the behavior that occurs when invalid params are submitted
        Creator.any_instance.stub(:save).and_return(false)
        post :create, :creator => {}
        assigns(:creator).should be_a_new(Creator)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Creator.any_instance.stub(:save).and_return(false)
        post :create, :creator => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested creator" do
        creator = Creator.create! valid_attributes
        # Assuming there are no other creators in the database, this
        # specifies that the Creator created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Creator.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => creator.id, :creator => {'these' => 'params'}
      end

      it "assigns the requested creator as @creator" do
        creator = Creator.create! valid_attributes
        put :update, :id => creator.id, :creator => valid_attributes
        assigns(:creator).should eq(creator)
      end

      it "redirects to the creator" do
        creator = Creator.create! valid_attributes
        put :update, :id => creator.id, :creator => valid_attributes
        response.should redirect_to(creator)
      end
    end

    describe "with invalid params" do
      it "assigns the creator as @creator" do
        creator = Creator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Creator.any_instance.stub(:save).and_return(false)
        put :update, :id => creator.id.to_s, :creator => {}
        assigns(:creator).should eq(creator)
      end

      it "re-renders the 'edit' template" do
        creator = Creator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Creator.any_instance.stub(:save).and_return(false)
        put :update, :id => creator.id.to_s, :creator => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested creator" do
      creator = Creator.create! valid_attributes
      expect {
        delete :destroy, :id => creator.id.to_s
      }.to change(Creator, :count).by(-1)
    end

    it "redirects to the creators list" do
      creator = Creator.create! valid_attributes
      delete :destroy, :id => creator.id.to_s
      response.should redirect_to(creators_url)
    end
  end

end
